# Generated by Django 5.2.11 on 2026-03-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioFiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='file',
            new_name='filename',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
