# Generated by Django 5.2.11 on 2026-03-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioFiles', '0002_rename_file_audiofile_filename_audiofile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='url',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='file_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
