# Generated by Django 5.2.11 on 2026-03-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioFiles', '0003_remove_audiofile_url_audiofile_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='transcription_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
