# Generated by Django 5.2.11 on 2026-03-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioFiles', '0004_audiofile_status_audiofile_transcription_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='s3_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
